# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'
  dockerId: emscontenedor
  pswd: ePrwU8FguIoaVPJVhG0dee5pRdrwHCD+
steps:
- script: |
    docker build -t $(dockerId).azurecr.io/nodep1:v1 .
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/nodep1:v1
  displayName: 'docker build'
